version: 2.1

orbs:
  discord: teka23/discord@0.0.1

jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - discord/notify:
          message: ":rocket: Building..."
          color: "16312092"

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Installing dependencies
          command: gradle dependencies

      - run:
          name: Running Build Tools
          command: gradle run-build-tools -PuseLocalDependency=false

      - save_cache:
          paths:
            - ~/.gradle
            - .build-tools
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      # run build
      - run:
          name: Building the plugins...
          command: gradle build-plugin

      - store_artifacts:
          path: server/plugins
          destination: ./build-artifacts

      - discord/status:
          fail_only: false
          failure_message: ":red_circle: The $CIRCLE_JOB job has failed!"
          success_message: ":tada: The $CIRCLE_JOB job has succeeded!"

  hold-for-publish:
    executor: discord/default
    steps:
      - discord/approval:
          message: ":raised_hand: Waiting for approval..."
          mentions: "216180750331019264"
          color: "16098851"

  publish-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./build-artifacts

      - discord/notify:
          message: ":rocket: Publishing..."
          color: "16312092"

      - run:
          name: "Publish Release on GitHub"
          command: "ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build-artifacts"

      - discord/status:
          fail_only: false
          failure_message: ":red_circle: Failed to publish $CIRCLE_PROJECT_REPONAME/$VERSION"
          success_message: ":tada: The $CIRCLE_PROJECT_REPONAME/$VERSION has been published successfully!"

workflows:
  version: 2.1

  main:
    jobs:
      - build
      - hold-for-publish:
          type: approval
          filters:
            branches:
              only:
                - release
          requires:
            - build
      - publish-release:
          filters:
            branches:
              only:
                - release
          requires:
            - build
